language: python
python:
  - "3.6"
  - "3.8"
before_install:
  - "pip install -U pip"
  - "pip install -e .[dev]"
install:
  - "pip install -e ."
addons:
script:
  - find . -iname "*.py" -and -not -path './.tox/*' -and -not -path './docs/*' | xargs pylint --rcfile=.pylintrc
  - python -m flake8
  - python3 -m pytest -m "not non_travis_test" .
  - mypy --config-file mypy.ini .
